export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";

export const GET_LIST_ACCOUNT_SUCCESS = "GET_LIST_ACCOUNT_SUCCESS";
export const GET_LIST_ACCOUNT_FAIL = "GET_LIST_ACCOUNT_FAIL";

export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";
export const GET_LIST_POST_FAIL = "GET_LIST_POST_FAIL";

export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_FAIL = "GET_POST_DETAIL_FAIL";
